# Generated by Django 2.1.5 on 2019-08-21 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('slug', models.CharField(max_length=50, verbose_name='Slug')),
                ('metadata', models.CharField(blank=True, max_length=20, null=True, verbose_name='TagName')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
            ],
            options={
                'verbose_name': 'ProyectoCategoria',
                'verbose_name_plural': 'ProyectoCategorias',
                'ordering': ['-created'],
            },
        ),
    ]
