# Generated by Django 2.1.5 on 2019-08-21 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_projectcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='metadata',
        ),
    ]
