# Generated by Django 2.1.5 on 2019-08-21 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_projectcategory_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='metadata',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='TagName'),
        ),
    ]
